stages:
  - package

package:
  stage: package
  image: python:3.10.0-alpine
  only:
    - main
  script:
    - python setup.py sdist bdist_wheel
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p $SSH_PASSWORD scp -r -oStrictHostKeyChecking=no dist/* $SSH_USER@$IPADDRESS:$LOCATION
