stages:
  - package
  - deploy

package:
  stage: package
  image: python:3.10.0-alpine
  only:
    - gitlab
  script:
    - python setup.py sdist bdist_wheel


deploy:
  stage: deploy
  only:
    - gitlab
  script:
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p mirnEn5BevOdjut scp -r -oStrictHostKeyChecking=no dist/* repo@192.168.160.21:/revproxy/updates/trinityx/12.2/luna2/noarch/pip/stable/cli
    - sshpass -p "$SSH_PASSWORD" scp -r -oStrictHostKeyChecking=no dist/* $env:SSH_USER@$env:IPADDRESS:$env:TEST_LOCATION
    - sshpass -p "$SSH_PASSWORD" scp -r -oStrictHostKeyChecking=no dist/* $SSH_USER@$IPADDRESS:$TEST_LOCATION
