#!/bin/sh

# This code is part of the TrinityX software suite
# Copyright (C) 2023  ClusterVision Solutions b.v.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

###
#
# Copy this file as /etc/bash_completion.d/luna and run su or loggin back
# And you'll get a bash completion for luna 
#
####

# AUTOMATICALLY GENERATED by `shtab`

_shtab_luna_subparsers=('cluster' 'network' 'osimage' 'bmcsetup' 'switch' 'otherdev' 'group' 'node' 'secrets' 'service' 'control' 'monitor')
_shtab_luna_cluster_subparsers=('change')
_shtab_luna_network_subparsers=('list' 'show' 'add' 'change' 'rename' 'remove' 'reserve' 'ipinfo' 'nextip' 'dns')
_shtab_luna_network_dns_subparsers=('add' 'change' 'remove')
_shtab_luna_osimage_subparsers=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove' 'pack' 'kernel' 'tag')
_shtab_luna_osimage_tag_subparsers=('show' 'change' 'remove')
_shtab_luna_bmcsetup_subparsers=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_switch_subparsers=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_otherdev_subparsers=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_group_subparsers=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove' 'ospush' 'listinterface' 'showinterface' 'changeinterface' 'removeinterface')
_shtab_luna_node_subparsers=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove' 'osgrab' 'ospush' 'listinterface' 'showinterface' 'changeinterface' 'removeinterface')
_shtab_luna_secrets_subparsers=('list' 'show' 'add' 'change' 'clone' 'remove')
_shtab_luna_secrets_list_subparsers=('node' 'group')
_shtab_luna_secrets_show_subparsers=('node' 'group')
_shtab_luna_secrets_add_subparsers=('node' 'group')
_shtab_luna_secrets_change_subparsers=('node' 'group')
_shtab_luna_secrets_clone_subparsers=('node' 'group')
_shtab_luna_secrets_remove_subparsers=('node' 'group')
_shtab_luna_service_subparsers=('dhcp' 'dns' 'luna2')
_shtab_luna_service_dhcp_subparsers=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_service_dns_subparsers=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_service_luna2_subparsers=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_control_subparsers=('power' 'sel' 'chassis' 'redfish')
_shtab_luna_control_power_subparsers=('on' 'off' 'status' 'reset')
_shtab_luna_control_sel_subparsers=('list' 'clear')
_shtab_luna_control_chassis_subparsers=('identify' 'noidentify')
_shtab_luna_control_redfish_subparsers=('upload' 'setting')
_shtab_luna_monitor_subparsers=('status' 'queue')

_shtab_luna_option_strings=('-h' '--help' '-V' '--version' '-v' '--verbose')
_shtab_luna_cluster_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_cluster_change_option_strings=('-h' '--help' '-v' '--verbose' '-n' '--name' '-u' '--user' '-ntp' '--ntp_server' '-o' '--createnode_ondemand' '-nx' '--nextnode_discover' '-ns' '--nameserver_ip' '-fs' '--forwardserver_ip' '-c' '--technical_contacts' '-pm' '--provision_method' '-pf' '--provision_fallback' '-s' '--security' '-d' '--debug')
_shtab_luna_network_option_strings=('-h' '--help')
_shtab_luna_network_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_network_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_network_add_option_strings=('-h' '--help' '-N' '--network' '-g' '--gateway' '-gm' '--gateway_metric' '-t' '--type' '-nsip' '--nameserver_ip' '-ntp' '--ntp_server' '-dhcp' '--dhcp' '-ds' '--dhcp_range_begin' '-de' '--dhcp_range_end' '-s' '--shared' '-z' '--zone' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_network_change_option_strings=('-h' '--help' '-N' '--network' '-g' '--gateway' '-gm' '--gateway_metric' '-t' '--type' '-nsip' '--nameserver_ip' '-ntp' '--ntp_server' '-dhcp' '--dhcp' '-ds' '--dhcp_range_begin' '-de' '--dhcp_range_end' '-s' '--shared' '-z' '--zone' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_network_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_reserve_option_strings=('-h' '--help' '-R' '--raw' '-v' '--verbose')
_shtab_luna_network_ipinfo_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_nextip_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_dns_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_network_dns_add_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_dns_change_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_network_dns_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_osimage_option_strings=('-h' '--help')
_shtab_luna_osimage_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_osimage_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_osimage_member_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_osimage_add_option_strings=('-h' '--help' '-gf' '--grab_filesystems' '-qgf' '--quick-grab_filesystems' '-ge' '--grab_exclude' '-qge' '--quick-grab_exclude' '-rd' '--initrdfile' '-k' '--kernelfile' '-m' '--kernelmodules' '-o' '--kerneloptions' '-qo' '--quick-kerneloptions' '-ver' '--kernelversion' '-p' '--path' '-img' '--imagefile' '-D' '--distribution' '-R' '--osrelease' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_osimage_change_option_strings=('-h' '--help' '-gf' '--grab_filesystems' '-qgf' '--quick-grab_filesystems' '-ge' '--grab_exclude' '-qge' '--quick-grab_exclude' '-rd' '--initrdfile' '-k' '--kernelfile' '-m' '--kernelmodules' '-o' '--kerneloptions' '-qo' '--quick-kerneloptions' '-ver' '--kernelversion' '-p' '--path' '-img' '--imagefile' '-D' '--distribution' '-R' '--osrelease' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose' '-t' '--tag')
_shtab_luna_osimage_clone_option_strings=('-h' '--help' '-gf' '--grab_filesystems' '-qgf' '--quick-grab_filesystems' '-ge' '--grab_exclude' '-qge' '--quick-grab_exclude' '-rd' '--initrdfile' '-k' '--kernelfile' '-m' '--kernelmodules' '-o' '--kerneloptions' '-qo' '--quick-kerneloptions' '-ver' '--kernelversion' '-p' '--path' '-img' '--imagefile' '-D' '--distribution' '-R' '--osrelease' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose' '-t' '--tag' '-nc' '--nocopy' '-b' '--bare')
_shtab_luna_osimage_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_osimage_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_osimage_pack_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_osimage_kernel_option_strings=('-h' '--help' '-rd' '--initrdfile' '-k' '--kernelfile' '-ver' '--kernelversion' '-b' '--bare' '-v' '--verbose')
_shtab_luna_osimage_tag_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_osimage_tag_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_osimage_tag_change_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_osimage_tag_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_bmcsetup_option_strings=('-h' '--help')
_shtab_luna_bmcsetup_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_bmcsetup_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_bmcsetup_member_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_bmcsetup_add_option_strings=('-h' '--help' '-uid' '--userid' '-u' '--username' '-p' '--password' '-nt' '--netchannel' '-mt' '--mgmtchannel' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_bmcsetup_change_option_strings=('-h' '--help' '-uid' '--userid' '-u' '--username' '-p' '--password' '-nt' '--netchannel' '-mt' '--mgmtchannel' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_bmcsetup_clone_option_strings=('-h' '--help' '-uid' '--userid' '-u' '--username' '-p' '--password' '-nt' '--netchannel' '-mt' '--mgmtchannel' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_bmcsetup_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_bmcsetup_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_switch_option_strings=('-h' '--help')
_shtab_luna_switch_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_switch_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_switch_add_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-r' '--read' '-w' '--rw' '-o' '--oid' '-u' '--uplinkports' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_switch_change_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-r' '--read' '-w' '--rw' '-o' '--oid' '-u' '--uplinkports' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_switch_clone_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-r' '--read' '-w' '--rw' '-o' '--oid' '-u' '--uplinkports' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_switch_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_switch_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_otherdev_option_strings=('-h' '--help')
_shtab_luna_otherdev_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_otherdev_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_otherdev_add_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_otherdev_change_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_otherdev_clone_option_strings=('-h' '--help' '-N' '--network' '-ip' '--ipaddress' '-m' '--macaddress' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_otherdev_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_otherdev_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_group_option_strings=('-h' '--help')
_shtab_luna_group_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_group_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_group_member_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_group_add_option_strings=('-h' '--help' '-b' '--setupbmc' '-o' '--osimage' '-ot' '--osimagetag' '-bmc' '--bmcsetupname' '-D' '--domain' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ubu' '--unmanaged_bmc_users' '-if' '--interface' '-N' '--network' '-O' '--options' '-qo' '--quick-options' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_group_change_option_strings=('-h' '--help' '-b' '--setupbmc' '-o' '--osimage' '-ot' '--osimagetag' '-bmc' '--bmcsetupname' '-D' '--domain' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ubu' '--unmanaged_bmc_users' '-if' '--interface' '-N' '--network' '-O' '--options' '-qo' '--quick-options' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_group_clone_option_strings=('-h' '--help' '-b' '--setupbmc' '-o' '--osimage' '-ot' '--osimagetag' '-bmc' '--bmcsetupname' '-D' '--domain' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ubu' '--unmanaged_bmc_users' '-if' '--interface' '-N' '--network' '-O' '--options' '-qo' '--quick-options' '-c' '--comment' '-qc' '--quick-comment' '-v' '--verbose')
_shtab_luna_group_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_group_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_group_ospush_option_strings=('-h' '--help' '-o' '--osimage' '-no' '--nodry' '-v' '--verbose')
_shtab_luna_group_listinterface_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_group_showinterface_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_group_changeinterface_option_strings=('-h' '--help' '-N' '--network' '-O' '--options' '-qo' '--quick-options' '-v' '--verbose')
_shtab_luna_group_removeinterface_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_node_option_strings=('-h' '--help')
_shtab_luna_node_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_node_show_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_node_add_option_strings=('-h' '--help' '-g' '--group' '-o' '--osimage' '-ot' '--osimagetag' '-b' '--setupbmc' '-bmc' '--bmcsetup' '-sw' '--switch' '-sp' '--switchport' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ser' '--service' '-s' '--status' '-tid' '--tpm_uuid' '-tkey' '--tpm_pubkey' '-tsha' '--tpm_sha256' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-if' '--interface' '-N' '--network' '-I' '--ipaddress' '-M' '--macaddress' '-O' '--options' '-qo' '--quick-options' '-v' '--verbose')
_shtab_luna_node_change_option_strings=('-h' '--help' '-g' '--group' '-o' '--osimage' '-ot' '--osimagetag' '-b' '--setupbmc' '-bmc' '--bmcsetup' '-sw' '--switch' '-sp' '--switchport' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ser' '--service' '-s' '--status' '-tid' '--tpm_uuid' '-tkey' '--tpm_pubkey' '-tsha' '--tpm_sha256' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-if' '--interface' '-N' '--network' '-I' '--ipaddress' '-M' '--macaddress' '-O' '--options' '-qo' '--quick-options' '-v' '--verbose')
_shtab_luna_node_clone_option_strings=('-h' '--help' '-g' '--group' '-o' '--osimage' '-ot' '--osimagetag' '-b' '--setupbmc' '-bmc' '--bmcsetup' '-sw' '--switch' '-sp' '--switchport' '-pre' '--prescript' '-qpre' '--quick-prescript' '-part' '--partscript' '-qpart' '--quick-partscript' '-post' '--postscript' '-qpost' '--quick-postscript' '-pi' '--provision_interface' '-pm' '--provision_method' '-fb' '--provision_fallback' '-nb' '--netboot' '-li' '--localinstall' '-bm' '--bootmenu' '-ser' '--service' '-s' '--status' '-tid' '--tpm_uuid' '-tkey' '--tpm_pubkey' '-tsha' '--tpm_sha256' '-ubu' '--unmanaged_bmc_users' '-c' '--comment' '-qc' '--quick-comment' '-if' '--interface' '-N' '--network' '-I' '--ipaddress' '-M' '--macaddress' '-O' '--options' '-qo' '--quick-options' '-v' '--verbose')
_shtab_luna_node_rename_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_node_remove_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_node_osgrab_option_strings=('-h' '--help' '-o' '--osimage' '-b' '--bare' '-no' '--nodry' '-v' '--verbose')
_shtab_luna_node_ospush_option_strings=('-h' '--help' '-o' '--osimage' '-no' '--nodry' '-v' '--verbose')
_shtab_luna_node_listinterface_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_node_showinterface_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_node_changeinterface_option_strings=('-h' '--help' '-N' '--network' '-I' '--ipaddress' '-M' '--macaddress' '-O' '--options' '-qo' '--quick-options' '-v' '--verbose')
_shtab_luna_node_removeinterface_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_secrets_option_strings=('-h' '--help')
_shtab_luna_secrets_list_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_secrets_list_node_option_strings=('-h' '--help' '-s' '--secret' '-R' '--raw' '-v' '--verbose')
_shtab_luna_secrets_list_group_option_strings=('-h' '--help' '-s' '--secret' '-R' '--raw' '-v' '--verbose')
_shtab_luna_secrets_show_option_strings=('-h' '--help')
_shtab_luna_secrets_show_node_option_strings=('-h' '--help' '-s' '--secret' '-R' '--raw' '-v' '--verbose')
_shtab_luna_secrets_show_group_option_strings=('-h' '--help' '-R' '--raw' '-v' '--verbose')
_shtab_luna_secrets_add_option_strings=('-h' '--help')
_shtab_luna_secrets_add_node_option_strings=('-h' '--help' '-c' '--content' '-qc' '--quick-content' '-p' '--path' '-v' '--verbose')
_shtab_luna_secrets_add_group_option_strings=('-h' '--help' '--content' '-c' '-qc' '--quick-content' '--path' '-p' '-v' '--verbose')
_shtab_luna_secrets_change_option_strings=('-h' '--help')
_shtab_luna_secrets_change_node_option_strings=('-h' '--help' '-c' '--content' '-qc' '--quick-content' '-p' '--path' '-v' '--verbose')
_shtab_luna_secrets_change_group_option_strings=('-h' '--help' '--content' '-c' '-qc' '--quick-content' '--path' '-p' '-v' '--verbose')
_shtab_luna_secrets_clone_option_strings=('-h' '--help')
_shtab_luna_secrets_clone_node_option_strings=('-h' '--help' '--content' '-c' '-qc' '--quick-content' '--path' '-p' '-v' '--verbose')
_shtab_luna_secrets_clone_group_option_strings=('-h' '--help' '--content' '-c' '-qc' '--quick-content' '--path' '-p' '-v' '--verbose')
_shtab_luna_secrets_remove_option_strings=('-h' '--help')
_shtab_luna_secrets_remove_node_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_secrets_remove_group_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_option_strings=('-h' '--help')
_shtab_luna_service_dhcp_option_strings=('-h' '--help')
_shtab_luna_service_dhcp_start_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dhcp_stop_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dhcp_restart_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dhcp_reload_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dhcp_status_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dns_option_strings=('-h' '--help')
_shtab_luna_service_dns_start_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dns_stop_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dns_restart_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dns_reload_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_dns_status_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_luna2_option_strings=('-h' '--help')
_shtab_luna_service_luna2_start_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_luna2_stop_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_luna2_restart_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_luna2_reload_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_service_luna2_status_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_option_strings=('-h' '--help')
_shtab_luna_control_power_option_strings=('-h' '--help')
_shtab_luna_control_power_on_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_power_off_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_power_status_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_power_reset_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_sel_option_strings=('-h' '--help')
_shtab_luna_control_sel_list_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_sel_clear_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_chassis_option_strings=('-h' '--help')
_shtab_luna_control_chassis_identify_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_chassis_noidentify_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_control_redfish_option_strings=('-h' '--help')
_shtab_luna_control_redfish_upload_option_strings=('-h' '--help' '-v' '--verbose' '-f' '--file')
_shtab_luna_control_redfish_setting_option_strings=('-h' '--help' '-v' '--verbose' '-f' '--file')
_shtab_luna_monitor_option_strings=('-h' '--help' '-v' '--verbose')
_shtab_luna_monitor_status_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')
_shtab_luna_monitor_queue_option_strings=('-h' '--help' '-v' '--verbose' '-R' '--raw')



_shtab_luna_pos_0_choices=('cluster' 'network' 'osimage' 'bmcsetup' 'switch' 'otherdev' 'group' 'node' 'secrets' 'service' 'control' 'monitor')
_shtab_luna_cluster_pos_0_choices=('change')
_shtab_luna_cluster_change__o_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change___createnode_ondemand_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change__nx_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change___nextnode_discover_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change__s_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change___security_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change__d_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_cluster_change___debug_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_network_pos_0_choices=('list' 'show' 'add' 'change' 'rename' 'remove' 'reserve' 'ipinfo' 'nextip' 'dns')
_shtab_luna_network_add__dhcp_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_network_add___dhcp_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_network_change__dhcp_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_network_change___dhcp_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_network_dns_pos_1_choices=('add' 'change' 'remove')
_shtab_luna_osimage_pos_0_choices=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove' 'pack' 'kernel' 'tag')
_shtab_luna_osimage_tag_pos_0_choices=('show' 'change' 'remove')
_shtab_luna_bmcsetup_pos_0_choices=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_switch_pos_0_choices=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_otherdev_pos_0_choices=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove')
_shtab_luna_group_pos_0_choices=('list' 'show' 'member' 'add' 'change' 'clone' 'rename' 'remove' 'ospush' 'listinterface' 'showinterface' 'changeinterface' 'removeinterface')
_shtab_luna_group_add__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_add___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_change___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_group_clone___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_pos_0_choices=('list' 'show' 'add' 'change' 'clone' 'rename' 'remove' 'osgrab' 'ospush' 'listinterface' 'showinterface' 'changeinterface' 'removeinterface')
_shtab_luna_node_add__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add__ser_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_add___service_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change__ser_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_change___service_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone__b_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone___setupbmc_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone__nb_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone___netboot_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone__li_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone___localinstall_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone__bm_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone___bootmenu_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone__ser_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_node_clone___service_choices=('y' 'yes' 'n' 'no' '')
_shtab_luna_secrets_pos_0_choices=('list' 'show' 'add' 'change' 'clone' 'remove')
_shtab_luna_secrets_list_pos_0_choices=('node' 'group')
_shtab_luna_secrets_show_pos_0_choices=('node' 'group')
_shtab_luna_secrets_add_pos_0_choices=('node' 'group')
_shtab_luna_secrets_change_pos_0_choices=('node' 'group')
_shtab_luna_secrets_clone_pos_0_choices=('node' 'group')
_shtab_luna_secrets_remove_pos_0_choices=('node' 'group')
_shtab_luna_service_pos_0_choices=('dhcp' 'dns' 'luna2')
_shtab_luna_service_dhcp_pos_0_choices=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_service_dns_pos_0_choices=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_service_luna2_pos_0_choices=('start' 'stop' 'restart' 'reload' 'status')
_shtab_luna_control_pos_0_choices=('power' 'sel' 'chassis' 'redfish')
_shtab_luna_control_power_pos_0_choices=('on' 'off' 'status' 'reset')
_shtab_luna_control_sel_pos_0_choices=('list' 'clear')
_shtab_luna_control_chassis_pos_0_choices=('identify' 'noidentify')
_shtab_luna_control_redfish_pos_0_choices=('upload' 'setting')
_shtab_luna_monitor_pos_0_choices=('status' 'queue')

_shtab_luna_pos_0_nargs=A...
_shtab_luna__h_nargs=0
_shtab_luna___help_nargs=0
_shtab_luna__V_nargs=0
_shtab_luna___version_nargs=0
_shtab_luna__v_nargs=0
_shtab_luna___verbose_nargs=0
_shtab_luna_cluster_pos_0_nargs=A...
_shtab_luna_cluster__h_nargs=0
_shtab_luna_cluster___help_nargs=0
_shtab_luna_cluster__v_nargs=0
_shtab_luna_cluster___verbose_nargs=0
_shtab_luna_cluster__R_nargs=0
_shtab_luna_cluster___raw_nargs=0
_shtab_luna_cluster_change__h_nargs=0
_shtab_luna_cluster_change___help_nargs=0
_shtab_luna_cluster_change__v_nargs=0
_shtab_luna_cluster_change___verbose_nargs=0
_shtab_luna_network_pos_0_nargs=A...
_shtab_luna_network__h_nargs=0
_shtab_luna_network___help_nargs=0
_shtab_luna_network_list__h_nargs=0
_shtab_luna_network_list___help_nargs=0
_shtab_luna_network_list__v_nargs=0
_shtab_luna_network_list___verbose_nargs=0
_shtab_luna_network_list__R_nargs=0
_shtab_luna_network_list___raw_nargs=0
_shtab_luna_network_show__h_nargs=0
_shtab_luna_network_show___help_nargs=0
_shtab_luna_network_show__v_nargs=0
_shtab_luna_network_show___verbose_nargs=0
_shtab_luna_network_show__R_nargs=0
_shtab_luna_network_show___raw_nargs=0
_shtab_luna_network_add__h_nargs=0
_shtab_luna_network_add___help_nargs=0
_shtab_luna_network_add__c_nargs=0
_shtab_luna_network_add___comment_nargs=0
_shtab_luna_network_add__v_nargs=0
_shtab_luna_network_add___verbose_nargs=0
_shtab_luna_network_change__h_nargs=0
_shtab_luna_network_change___help_nargs=0
_shtab_luna_network_change__c_nargs=0
_shtab_luna_network_change___comment_nargs=0
_shtab_luna_network_change__v_nargs=0
_shtab_luna_network_change___verbose_nargs=0
_shtab_luna_network_rename__h_nargs=0
_shtab_luna_network_rename___help_nargs=0
_shtab_luna_network_rename__v_nargs=0
_shtab_luna_network_rename___verbose_nargs=0
_shtab_luna_network_remove__h_nargs=0
_shtab_luna_network_remove___help_nargs=0
_shtab_luna_network_remove__v_nargs=0
_shtab_luna_network_remove___verbose_nargs=0
_shtab_luna_network_reserve__h_nargs=0
_shtab_luna_network_reserve___help_nargs=0
_shtab_luna_network_reserve__R_nargs=0
_shtab_luna_network_reserve___raw_nargs=0
_shtab_luna_network_reserve__v_nargs=0
_shtab_luna_network_reserve___verbose_nargs=0
_shtab_luna_network_ipinfo__h_nargs=0
_shtab_luna_network_ipinfo___help_nargs=0
_shtab_luna_network_ipinfo__v_nargs=0
_shtab_luna_network_ipinfo___verbose_nargs=0
_shtab_luna_network_nextip__h_nargs=0
_shtab_luna_network_nextip___help_nargs=0
_shtab_luna_network_nextip__v_nargs=0
_shtab_luna_network_nextip___verbose_nargs=0
_shtab_luna_network_dns_pos_1_nargs=A...
_shtab_luna_network_dns__h_nargs=0
_shtab_luna_network_dns___help_nargs=0
_shtab_luna_network_dns__v_nargs=0
_shtab_luna_network_dns___verbose_nargs=0
_shtab_luna_network_dns__R_nargs=0
_shtab_luna_network_dns___raw_nargs=0
_shtab_luna_network_dns_add__h_nargs=0
_shtab_luna_network_dns_add___help_nargs=0
_shtab_luna_network_dns_add__v_nargs=0
_shtab_luna_network_dns_add___verbose_nargs=0
_shtab_luna_network_dns_change__h_nargs=0
_shtab_luna_network_dns_change___help_nargs=0
_shtab_luna_network_dns_change__v_nargs=0
_shtab_luna_network_dns_change___verbose_nargs=0
_shtab_luna_network_dns_remove__h_nargs=0
_shtab_luna_network_dns_remove___help_nargs=0
_shtab_luna_network_dns_remove__v_nargs=0
_shtab_luna_network_dns_remove___verbose_nargs=0
_shtab_luna_osimage_pos_0_nargs=A...
_shtab_luna_osimage__h_nargs=0
_shtab_luna_osimage___help_nargs=0
_shtab_luna_osimage_list__h_nargs=0
_shtab_luna_osimage_list___help_nargs=0
_shtab_luna_osimage_list__v_nargs=0
_shtab_luna_osimage_list___verbose_nargs=0
_shtab_luna_osimage_list__R_nargs=0
_shtab_luna_osimage_list___raw_nargs=0
_shtab_luna_osimage_show__h_nargs=0
_shtab_luna_osimage_show___help_nargs=0
_shtab_luna_osimage_show__v_nargs=0
_shtab_luna_osimage_show___verbose_nargs=0
_shtab_luna_osimage_show__R_nargs=0
_shtab_luna_osimage_show___raw_nargs=0
_shtab_luna_osimage_member__h_nargs=0
_shtab_luna_osimage_member___help_nargs=0
_shtab_luna_osimage_member__v_nargs=0
_shtab_luna_osimage_member___verbose_nargs=0
_shtab_luna_osimage_member__R_nargs=0
_shtab_luna_osimage_member___raw_nargs=0
_shtab_luna_osimage_add__h_nargs=0
_shtab_luna_osimage_add___help_nargs=0
_shtab_luna_osimage_add__gf_nargs=0
_shtab_luna_osimage_add___grab_filesystems_nargs=0
_shtab_luna_osimage_add__ge_nargs=0
_shtab_luna_osimage_add___grab_exclude_nargs=0
_shtab_luna_osimage_add__o_nargs=0
_shtab_luna_osimage_add___kerneloptions_nargs=0
_shtab_luna_osimage_add__c_nargs=0
_shtab_luna_osimage_add___comment_nargs=0
_shtab_luna_osimage_add__v_nargs=0
_shtab_luna_osimage_add___verbose_nargs=0
_shtab_luna_osimage_change__h_nargs=0
_shtab_luna_osimage_change___help_nargs=0
_shtab_luna_osimage_change__gf_nargs=0
_shtab_luna_osimage_change___grab_filesystems_nargs=0
_shtab_luna_osimage_change__ge_nargs=0
_shtab_luna_osimage_change___grab_exclude_nargs=0
_shtab_luna_osimage_change__o_nargs=0
_shtab_luna_osimage_change___kerneloptions_nargs=0
_shtab_luna_osimage_change__c_nargs=0
_shtab_luna_osimage_change___comment_nargs=0
_shtab_luna_osimage_change__v_nargs=0
_shtab_luna_osimage_change___verbose_nargs=0
_shtab_luna_osimage_clone__h_nargs=0
_shtab_luna_osimage_clone___help_nargs=0
_shtab_luna_osimage_clone__gf_nargs=0
_shtab_luna_osimage_clone___grab_filesystems_nargs=0
_shtab_luna_osimage_clone__ge_nargs=0
_shtab_luna_osimage_clone___grab_exclude_nargs=0
_shtab_luna_osimage_clone__o_nargs=0
_shtab_luna_osimage_clone___kerneloptions_nargs=0
_shtab_luna_osimage_clone__c_nargs=0
_shtab_luna_osimage_clone___comment_nargs=0
_shtab_luna_osimage_clone__v_nargs=0
_shtab_luna_osimage_clone___verbose_nargs=0
_shtab_luna_osimage_clone__nc_nargs=0
_shtab_luna_osimage_clone___nocopy_nargs=0
_shtab_luna_osimage_clone__b_nargs=0
_shtab_luna_osimage_clone___bare_nargs=0
_shtab_luna_osimage_rename__h_nargs=0
_shtab_luna_osimage_rename___help_nargs=0
_shtab_luna_osimage_rename__v_nargs=0
_shtab_luna_osimage_rename___verbose_nargs=0
_shtab_luna_osimage_remove__h_nargs=0
_shtab_luna_osimage_remove___help_nargs=0
_shtab_luna_osimage_remove__v_nargs=0
_shtab_luna_osimage_remove___verbose_nargs=0
_shtab_luna_osimage_pack__h_nargs=0
_shtab_luna_osimage_pack___help_nargs=0
_shtab_luna_osimage_pack__v_nargs=0
_shtab_luna_osimage_pack___verbose_nargs=0
_shtab_luna_osimage_kernel__h_nargs=0
_shtab_luna_osimage_kernel___help_nargs=0
_shtab_luna_osimage_kernel__b_nargs=0
_shtab_luna_osimage_kernel___bare_nargs=0
_shtab_luna_osimage_kernel__v_nargs=0
_shtab_luna_osimage_kernel___verbose_nargs=0
_shtab_luna_osimage_tag_pos_0_nargs=A...
_shtab_luna_osimage_tag__h_nargs=0
_shtab_luna_osimage_tag___help_nargs=0
_shtab_luna_osimage_tag__v_nargs=0
_shtab_luna_osimage_tag___verbose_nargs=0
_shtab_luna_osimage_tag__R_nargs=0
_shtab_luna_osimage_tag___raw_nargs=0
_shtab_luna_osimage_tag_show__h_nargs=0
_shtab_luna_osimage_tag_show___help_nargs=0
_shtab_luna_osimage_tag_show__v_nargs=0
_shtab_luna_osimage_tag_show___verbose_nargs=0
_shtab_luna_osimage_tag_show__R_nargs=0
_shtab_luna_osimage_tag_show___raw_nargs=0
_shtab_luna_osimage_tag_change__h_nargs=0
_shtab_luna_osimage_tag_change___help_nargs=0
_shtab_luna_osimage_tag_change__v_nargs=0
_shtab_luna_osimage_tag_change___verbose_nargs=0
_shtab_luna_osimage_tag_remove__h_nargs=0
_shtab_luna_osimage_tag_remove___help_nargs=0
_shtab_luna_osimage_tag_remove__v_nargs=0
_shtab_luna_osimage_tag_remove___verbose_nargs=0
_shtab_luna_bmcsetup_pos_0_nargs=A...
_shtab_luna_bmcsetup__h_nargs=0
_shtab_luna_bmcsetup___help_nargs=0
_shtab_luna_bmcsetup_list__h_nargs=0
_shtab_luna_bmcsetup_list___help_nargs=0
_shtab_luna_bmcsetup_list__v_nargs=0
_shtab_luna_bmcsetup_list___verbose_nargs=0
_shtab_luna_bmcsetup_list__R_nargs=0
_shtab_luna_bmcsetup_list___raw_nargs=0
_shtab_luna_bmcsetup_show__h_nargs=0
_shtab_luna_bmcsetup_show___help_nargs=0
_shtab_luna_bmcsetup_show__v_nargs=0
_shtab_luna_bmcsetup_show___verbose_nargs=0
_shtab_luna_bmcsetup_show__R_nargs=0
_shtab_luna_bmcsetup_show___raw_nargs=0
_shtab_luna_bmcsetup_member__h_nargs=0
_shtab_luna_bmcsetup_member___help_nargs=0
_shtab_luna_bmcsetup_member__v_nargs=0
_shtab_luna_bmcsetup_member___verbose_nargs=0
_shtab_luna_bmcsetup_member__R_nargs=0
_shtab_luna_bmcsetup_member___raw_nargs=0
_shtab_luna_bmcsetup_add__h_nargs=0
_shtab_luna_bmcsetup_add___help_nargs=0
_shtab_luna_bmcsetup_add__c_nargs=0
_shtab_luna_bmcsetup_add___comment_nargs=0
_shtab_luna_bmcsetup_add__v_nargs=0
_shtab_luna_bmcsetup_add___verbose_nargs=0
_shtab_luna_bmcsetup_change__h_nargs=0
_shtab_luna_bmcsetup_change___help_nargs=0
_shtab_luna_bmcsetup_change__c_nargs=0
_shtab_luna_bmcsetup_change___comment_nargs=0
_shtab_luna_bmcsetup_change__v_nargs=0
_shtab_luna_bmcsetup_change___verbose_nargs=0
_shtab_luna_bmcsetup_clone__h_nargs=0
_shtab_luna_bmcsetup_clone___help_nargs=0
_shtab_luna_bmcsetup_clone__c_nargs=0
_shtab_luna_bmcsetup_clone___comment_nargs=0
_shtab_luna_bmcsetup_clone__v_nargs=0
_shtab_luna_bmcsetup_clone___verbose_nargs=0
_shtab_luna_bmcsetup_rename__h_nargs=0
_shtab_luna_bmcsetup_rename___help_nargs=0
_shtab_luna_bmcsetup_rename__v_nargs=0
_shtab_luna_bmcsetup_rename___verbose_nargs=0
_shtab_luna_bmcsetup_remove__h_nargs=0
_shtab_luna_bmcsetup_remove___help_nargs=0
_shtab_luna_bmcsetup_remove__v_nargs=0
_shtab_luna_bmcsetup_remove___verbose_nargs=0
_shtab_luna_switch_pos_0_nargs=A...
_shtab_luna_switch__h_nargs=0
_shtab_luna_switch___help_nargs=0
_shtab_luna_switch_list__h_nargs=0
_shtab_luna_switch_list___help_nargs=0
_shtab_luna_switch_list__v_nargs=0
_shtab_luna_switch_list___verbose_nargs=0
_shtab_luna_switch_list__R_nargs=0
_shtab_luna_switch_list___raw_nargs=0
_shtab_luna_switch_show__h_nargs=0
_shtab_luna_switch_show___help_nargs=0
_shtab_luna_switch_show__v_nargs=0
_shtab_luna_switch_show___verbose_nargs=0
_shtab_luna_switch_show__R_nargs=0
_shtab_luna_switch_show___raw_nargs=0
_shtab_luna_switch_add__h_nargs=0
_shtab_luna_switch_add___help_nargs=0
_shtab_luna_switch_add__c_nargs=0
_shtab_luna_switch_add___comment_nargs=0
_shtab_luna_switch_add__v_nargs=0
_shtab_luna_switch_add___verbose_nargs=0
_shtab_luna_switch_change__h_nargs=0
_shtab_luna_switch_change___help_nargs=0
_shtab_luna_switch_change__c_nargs=0
_shtab_luna_switch_change___comment_nargs=0
_shtab_luna_switch_change__v_nargs=0
_shtab_luna_switch_change___verbose_nargs=0
_shtab_luna_switch_clone__h_nargs=0
_shtab_luna_switch_clone___help_nargs=0
_shtab_luna_switch_clone__c_nargs=0
_shtab_luna_switch_clone___comment_nargs=0
_shtab_luna_switch_clone__v_nargs=0
_shtab_luna_switch_clone___verbose_nargs=0
_shtab_luna_switch_rename__h_nargs=0
_shtab_luna_switch_rename___help_nargs=0
_shtab_luna_switch_rename__v_nargs=0
_shtab_luna_switch_rename___verbose_nargs=0
_shtab_luna_switch_remove__h_nargs=0
_shtab_luna_switch_remove___help_nargs=0
_shtab_luna_switch_remove__v_nargs=0
_shtab_luna_switch_remove___verbose_nargs=0
_shtab_luna_otherdev_pos_0_nargs=A...
_shtab_luna_otherdev__h_nargs=0
_shtab_luna_otherdev___help_nargs=0
_shtab_luna_otherdev_list__h_nargs=0
_shtab_luna_otherdev_list___help_nargs=0
_shtab_luna_otherdev_list__v_nargs=0
_shtab_luna_otherdev_list___verbose_nargs=0
_shtab_luna_otherdev_list__R_nargs=0
_shtab_luna_otherdev_list___raw_nargs=0
_shtab_luna_otherdev_show__h_nargs=0
_shtab_luna_otherdev_show___help_nargs=0
_shtab_luna_otherdev_show__v_nargs=0
_shtab_luna_otherdev_show___verbose_nargs=0
_shtab_luna_otherdev_show__R_nargs=0
_shtab_luna_otherdev_show___raw_nargs=0
_shtab_luna_otherdev_add__h_nargs=0
_shtab_luna_otherdev_add___help_nargs=0
_shtab_luna_otherdev_add__c_nargs=0
_shtab_luna_otherdev_add___comment_nargs=0
_shtab_luna_otherdev_add__v_nargs=0
_shtab_luna_otherdev_add___verbose_nargs=0
_shtab_luna_otherdev_change__h_nargs=0
_shtab_luna_otherdev_change___help_nargs=0
_shtab_luna_otherdev_change__c_nargs=0
_shtab_luna_otherdev_change___comment_nargs=0
_shtab_luna_otherdev_change__v_nargs=0
_shtab_luna_otherdev_change___verbose_nargs=0
_shtab_luna_otherdev_clone__h_nargs=0
_shtab_luna_otherdev_clone___help_nargs=0
_shtab_luna_otherdev_clone__c_nargs=0
_shtab_luna_otherdev_clone___comment_nargs=0
_shtab_luna_otherdev_clone__v_nargs=0
_shtab_luna_otherdev_clone___verbose_nargs=0
_shtab_luna_otherdev_rename__h_nargs=0
_shtab_luna_otherdev_rename___help_nargs=0
_shtab_luna_otherdev_rename__v_nargs=0
_shtab_luna_otherdev_rename___verbose_nargs=0
_shtab_luna_otherdev_remove__h_nargs=0
_shtab_luna_otherdev_remove___help_nargs=0
_shtab_luna_otherdev_remove__v_nargs=0
_shtab_luna_otherdev_remove___verbose_nargs=0
_shtab_luna_group_pos_0_nargs=A...
_shtab_luna_group__h_nargs=0
_shtab_luna_group___help_nargs=0
_shtab_luna_group_list__h_nargs=0
_shtab_luna_group_list___help_nargs=0
_shtab_luna_group_list__v_nargs=0
_shtab_luna_group_list___verbose_nargs=0
_shtab_luna_group_list__R_nargs=0
_shtab_luna_group_list___raw_nargs=0
_shtab_luna_group_show__h_nargs=0
_shtab_luna_group_show___help_nargs=0
_shtab_luna_group_show__v_nargs=0
_shtab_luna_group_show___verbose_nargs=0
_shtab_luna_group_show__R_nargs=0
_shtab_luna_group_show___raw_nargs=0
_shtab_luna_group_member__h_nargs=0
_shtab_luna_group_member___help_nargs=0
_shtab_luna_group_member__v_nargs=0
_shtab_luna_group_member___verbose_nargs=0
_shtab_luna_group_member__R_nargs=0
_shtab_luna_group_member___raw_nargs=0
_shtab_luna_group_add__h_nargs=0
_shtab_luna_group_add___help_nargs=0
_shtab_luna_group_add__pre_nargs=0
_shtab_luna_group_add___prescript_nargs=0
_shtab_luna_group_add__part_nargs=0
_shtab_luna_group_add___partscript_nargs=0
_shtab_luna_group_add__post_nargs=0
_shtab_luna_group_add___postscript_nargs=0
_shtab_luna_group_add__O_nargs=0
_shtab_luna_group_add___options_nargs=0
_shtab_luna_group_add__c_nargs=0
_shtab_luna_group_add___comment_nargs=0
_shtab_luna_group_add__v_nargs=0
_shtab_luna_group_add___verbose_nargs=0
_shtab_luna_group_change__h_nargs=0
_shtab_luna_group_change___help_nargs=0
_shtab_luna_group_change__pre_nargs=0
_shtab_luna_group_change___prescript_nargs=0
_shtab_luna_group_change__part_nargs=0
_shtab_luna_group_change___partscript_nargs=0
_shtab_luna_group_change__post_nargs=0
_shtab_luna_group_change___postscript_nargs=0
_shtab_luna_group_change__O_nargs=0
_shtab_luna_group_change___options_nargs=0
_shtab_luna_group_change__c_nargs=0
_shtab_luna_group_change___comment_nargs=0
_shtab_luna_group_change__v_nargs=0
_shtab_luna_group_change___verbose_nargs=0
_shtab_luna_group_clone__h_nargs=0
_shtab_luna_group_clone___help_nargs=0
_shtab_luna_group_clone__pre_nargs=0
_shtab_luna_group_clone___prescript_nargs=0
_shtab_luna_group_clone__part_nargs=0
_shtab_luna_group_clone___partscript_nargs=0
_shtab_luna_group_clone__post_nargs=0
_shtab_luna_group_clone___postscript_nargs=0
_shtab_luna_group_clone__O_nargs=0
_shtab_luna_group_clone___options_nargs=0
_shtab_luna_group_clone__c_nargs=0
_shtab_luna_group_clone___comment_nargs=0
_shtab_luna_group_clone__v_nargs=0
_shtab_luna_group_clone___verbose_nargs=0
_shtab_luna_group_rename__h_nargs=0
_shtab_luna_group_rename___help_nargs=0
_shtab_luna_group_rename__v_nargs=0
_shtab_luna_group_rename___verbose_nargs=0
_shtab_luna_group_remove__h_nargs=0
_shtab_luna_group_remove___help_nargs=0
_shtab_luna_group_remove__v_nargs=0
_shtab_luna_group_remove___verbose_nargs=0
_shtab_luna_group_ospush__h_nargs=0
_shtab_luna_group_ospush___help_nargs=0
_shtab_luna_group_ospush__no_nargs=0
_shtab_luna_group_ospush___nodry_nargs=0
_shtab_luna_group_ospush__v_nargs=0
_shtab_luna_group_ospush___verbose_nargs=0
_shtab_luna_group_listinterface__h_nargs=0
_shtab_luna_group_listinterface___help_nargs=0
_shtab_luna_group_listinterface__v_nargs=0
_shtab_luna_group_listinterface___verbose_nargs=0
_shtab_luna_group_listinterface__R_nargs=0
_shtab_luna_group_listinterface___raw_nargs=0
_shtab_luna_group_showinterface__h_nargs=0
_shtab_luna_group_showinterface___help_nargs=0
_shtab_luna_group_showinterface__v_nargs=0
_shtab_luna_group_showinterface___verbose_nargs=0
_shtab_luna_group_showinterface__R_nargs=0
_shtab_luna_group_showinterface___raw_nargs=0
_shtab_luna_group_changeinterface__h_nargs=0
_shtab_luna_group_changeinterface___help_nargs=0
_shtab_luna_group_changeinterface__O_nargs=0
_shtab_luna_group_changeinterface___options_nargs=0
_shtab_luna_group_changeinterface__v_nargs=0
_shtab_luna_group_changeinterface___verbose_nargs=0
_shtab_luna_group_removeinterface__h_nargs=0
_shtab_luna_group_removeinterface___help_nargs=0
_shtab_luna_group_removeinterface__v_nargs=0
_shtab_luna_group_removeinterface___verbose_nargs=0
_shtab_luna_node_pos_0_nargs=A...
_shtab_luna_node__h_nargs=0
_shtab_luna_node___help_nargs=0
_shtab_luna_node_list__h_nargs=0
_shtab_luna_node_list___help_nargs=0
_shtab_luna_node_list__v_nargs=0
_shtab_luna_node_list___verbose_nargs=0
_shtab_luna_node_list__R_nargs=0
_shtab_luna_node_list___raw_nargs=0
_shtab_luna_node_show__h_nargs=0
_shtab_luna_node_show___help_nargs=0
_shtab_luna_node_show__v_nargs=0
_shtab_luna_node_show___verbose_nargs=0
_shtab_luna_node_show__R_nargs=0
_shtab_luna_node_show___raw_nargs=0
_shtab_luna_node_add__h_nargs=0
_shtab_luna_node_add___help_nargs=0
_shtab_luna_node_add__pre_nargs=0
_shtab_luna_node_add___prescript_nargs=0
_shtab_luna_node_add__part_nargs=0
_shtab_luna_node_add___partscript_nargs=0
_shtab_luna_node_add__post_nargs=0
_shtab_luna_node_add___postscript_nargs=0
_shtab_luna_node_add__c_nargs=0
_shtab_luna_node_add___comment_nargs=0
_shtab_luna_node_add__O_nargs=0
_shtab_luna_node_add___options_nargs=0
_shtab_luna_node_add__v_nargs=0
_shtab_luna_node_add___verbose_nargs=0
_shtab_luna_node_change__h_nargs=0
_shtab_luna_node_change___help_nargs=0
_shtab_luna_node_change__pre_nargs=0
_shtab_luna_node_change___prescript_nargs=0
_shtab_luna_node_change__part_nargs=0
_shtab_luna_node_change___partscript_nargs=0
_shtab_luna_node_change__post_nargs=0
_shtab_luna_node_change___postscript_nargs=0
_shtab_luna_node_change__c_nargs=0
_shtab_luna_node_change___comment_nargs=0
_shtab_luna_node_change__O_nargs=0
_shtab_luna_node_change___options_nargs=0
_shtab_luna_node_change__v_nargs=0
_shtab_luna_node_change___verbose_nargs=0
_shtab_luna_node_clone__h_nargs=0
_shtab_luna_node_clone___help_nargs=0
_shtab_luna_node_clone__pre_nargs=0
_shtab_luna_node_clone___prescript_nargs=0
_shtab_luna_node_clone__part_nargs=0
_shtab_luna_node_clone___partscript_nargs=0
_shtab_luna_node_clone__post_nargs=0
_shtab_luna_node_clone___postscript_nargs=0
_shtab_luna_node_clone__c_nargs=0
_shtab_luna_node_clone___comment_nargs=0
_shtab_luna_node_clone__O_nargs=0
_shtab_luna_node_clone___options_nargs=0
_shtab_luna_node_clone__v_nargs=0
_shtab_luna_node_clone___verbose_nargs=0
_shtab_luna_node_rename__h_nargs=0
_shtab_luna_node_rename___help_nargs=0
_shtab_luna_node_rename__v_nargs=0
_shtab_luna_node_rename___verbose_nargs=0
_shtab_luna_node_remove__h_nargs=0
_shtab_luna_node_remove___help_nargs=0
_shtab_luna_node_remove__v_nargs=0
_shtab_luna_node_remove___verbose_nargs=0
_shtab_luna_node_osgrab__h_nargs=0
_shtab_luna_node_osgrab___help_nargs=0
_shtab_luna_node_osgrab__b_nargs=0
_shtab_luna_node_osgrab___bare_nargs=0
_shtab_luna_node_osgrab__no_nargs=0
_shtab_luna_node_osgrab___nodry_nargs=0
_shtab_luna_node_osgrab__v_nargs=0
_shtab_luna_node_osgrab___verbose_nargs=0
_shtab_luna_node_ospush__h_nargs=0
_shtab_luna_node_ospush___help_nargs=0
_shtab_luna_node_ospush__no_nargs=0
_shtab_luna_node_ospush___nodry_nargs=0
_shtab_luna_node_ospush__v_nargs=0
_shtab_luna_node_ospush___verbose_nargs=0
_shtab_luna_node_listinterface__h_nargs=0
_shtab_luna_node_listinterface___help_nargs=0
_shtab_luna_node_listinterface__v_nargs=0
_shtab_luna_node_listinterface___verbose_nargs=0
_shtab_luna_node_listinterface__R_nargs=0
_shtab_luna_node_listinterface___raw_nargs=0
_shtab_luna_node_showinterface__h_nargs=0
_shtab_luna_node_showinterface___help_nargs=0
_shtab_luna_node_showinterface__v_nargs=0
_shtab_luna_node_showinterface___verbose_nargs=0
_shtab_luna_node_showinterface__R_nargs=0
_shtab_luna_node_showinterface___raw_nargs=0
_shtab_luna_node_changeinterface__h_nargs=0
_shtab_luna_node_changeinterface___help_nargs=0
_shtab_luna_node_changeinterface__O_nargs=0
_shtab_luna_node_changeinterface___options_nargs=0
_shtab_luna_node_changeinterface__v_nargs=0
_shtab_luna_node_changeinterface___verbose_nargs=0
_shtab_luna_node_removeinterface__h_nargs=0
_shtab_luna_node_removeinterface___help_nargs=0
_shtab_luna_node_removeinterface__v_nargs=0
_shtab_luna_node_removeinterface___verbose_nargs=0
_shtab_luna_secrets_pos_0_nargs=A...
_shtab_luna_secrets__h_nargs=0
_shtab_luna_secrets___help_nargs=0
_shtab_luna_secrets_list_pos_0_nargs=A...
_shtab_luna_secrets_list__h_nargs=0
_shtab_luna_secrets_list___help_nargs=0
_shtab_luna_secrets_list__v_nargs=0
_shtab_luna_secrets_list___verbose_nargs=0
_shtab_luna_secrets_list__R_nargs=0
_shtab_luna_secrets_list___raw_nargs=0
_shtab_luna_secrets_list_node__h_nargs=0
_shtab_luna_secrets_list_node___help_nargs=0
_shtab_luna_secrets_list_node__R_nargs=0
_shtab_luna_secrets_list_node___raw_nargs=0
_shtab_luna_secrets_list_node__v_nargs=0
_shtab_luna_secrets_list_node___verbose_nargs=0
_shtab_luna_secrets_list_group__h_nargs=0
_shtab_luna_secrets_list_group___help_nargs=0
_shtab_luna_secrets_list_group__R_nargs=0
_shtab_luna_secrets_list_group___raw_nargs=0
_shtab_luna_secrets_list_group__v_nargs=0
_shtab_luna_secrets_list_group___verbose_nargs=0
_shtab_luna_secrets_show_pos_0_nargs=A...
_shtab_luna_secrets_show__h_nargs=0
_shtab_luna_secrets_show___help_nargs=0
_shtab_luna_secrets_show_node__h_nargs=0
_shtab_luna_secrets_show_node___help_nargs=0
_shtab_luna_secrets_show_node__R_nargs=0
_shtab_luna_secrets_show_node___raw_nargs=0
_shtab_luna_secrets_show_node__v_nargs=0
_shtab_luna_secrets_show_node___verbose_nargs=0
_shtab_luna_secrets_show_group__h_nargs=0
_shtab_luna_secrets_show_group___help_nargs=0
_shtab_luna_secrets_show_group__R_nargs=0
_shtab_luna_secrets_show_group___raw_nargs=0
_shtab_luna_secrets_show_group__v_nargs=0
_shtab_luna_secrets_show_group___verbose_nargs=0
_shtab_luna_secrets_add_pos_0_nargs=A...
_shtab_luna_secrets_add__h_nargs=0
_shtab_luna_secrets_add___help_nargs=0
_shtab_luna_secrets_add_node__h_nargs=0
_shtab_luna_secrets_add_node___help_nargs=0
_shtab_luna_secrets_add_node__c_nargs=0
_shtab_luna_secrets_add_node___content_nargs=0
_shtab_luna_secrets_add_node__v_nargs=0
_shtab_luna_secrets_add_node___verbose_nargs=0
_shtab_luna_secrets_add_group__h_nargs=0
_shtab_luna_secrets_add_group___help_nargs=0
_shtab_luna_secrets_add_group___content_nargs=0
_shtab_luna_secrets_add_group__c_nargs=0
_shtab_luna_secrets_add_group__v_nargs=0
_shtab_luna_secrets_add_group___verbose_nargs=0
_shtab_luna_secrets_change_pos_0_nargs=A...
_shtab_luna_secrets_change__h_nargs=0
_shtab_luna_secrets_change___help_nargs=0
_shtab_luna_secrets_change_node__h_nargs=0
_shtab_luna_secrets_change_node___help_nargs=0
_shtab_luna_secrets_change_node__c_nargs=0
_shtab_luna_secrets_change_node___content_nargs=0
_shtab_luna_secrets_change_node__v_nargs=0
_shtab_luna_secrets_change_node___verbose_nargs=0
_shtab_luna_secrets_change_group__h_nargs=0
_shtab_luna_secrets_change_group___help_nargs=0
_shtab_luna_secrets_change_group___content_nargs=0
_shtab_luna_secrets_change_group__c_nargs=0
_shtab_luna_secrets_change_group__v_nargs=0
_shtab_luna_secrets_change_group___verbose_nargs=0
_shtab_luna_secrets_clone_pos_0_nargs=A...
_shtab_luna_secrets_clone__h_nargs=0
_shtab_luna_secrets_clone___help_nargs=0
_shtab_luna_secrets_clone_node__h_nargs=0
_shtab_luna_secrets_clone_node___help_nargs=0
_shtab_luna_secrets_clone_node___content_nargs=0
_shtab_luna_secrets_clone_node__c_nargs=0
_shtab_luna_secrets_clone_node__v_nargs=0
_shtab_luna_secrets_clone_node___verbose_nargs=0
_shtab_luna_secrets_clone_group__h_nargs=0
_shtab_luna_secrets_clone_group___help_nargs=0
_shtab_luna_secrets_clone_group___content_nargs=0
_shtab_luna_secrets_clone_group__c_nargs=0
_shtab_luna_secrets_clone_group__v_nargs=0
_shtab_luna_secrets_clone_group___verbose_nargs=0
_shtab_luna_secrets_remove_pos_0_nargs=A...
_shtab_luna_secrets_remove__h_nargs=0
_shtab_luna_secrets_remove___help_nargs=0
_shtab_luna_secrets_remove_node__h_nargs=0
_shtab_luna_secrets_remove_node___help_nargs=0
_shtab_luna_secrets_remove_node__v_nargs=0
_shtab_luna_secrets_remove_node___verbose_nargs=0
_shtab_luna_secrets_remove_group__h_nargs=0
_shtab_luna_secrets_remove_group___help_nargs=0
_shtab_luna_secrets_remove_group__v_nargs=0
_shtab_luna_secrets_remove_group___verbose_nargs=0
_shtab_luna_service_pos_0_nargs=A...
_shtab_luna_service__h_nargs=0
_shtab_luna_service___help_nargs=0
_shtab_luna_service_dhcp_pos_0_nargs=A...
_shtab_luna_service_dhcp__h_nargs=0
_shtab_luna_service_dhcp___help_nargs=0
_shtab_luna_service_dhcp_start__h_nargs=0
_shtab_luna_service_dhcp_start___help_nargs=0
_shtab_luna_service_dhcp_start__v_nargs=0
_shtab_luna_service_dhcp_start___verbose_nargs=0
_shtab_luna_service_dhcp_stop__h_nargs=0
_shtab_luna_service_dhcp_stop___help_nargs=0
_shtab_luna_service_dhcp_stop__v_nargs=0
_shtab_luna_service_dhcp_stop___verbose_nargs=0
_shtab_luna_service_dhcp_restart__h_nargs=0
_shtab_luna_service_dhcp_restart___help_nargs=0
_shtab_luna_service_dhcp_restart__v_nargs=0
_shtab_luna_service_dhcp_restart___verbose_nargs=0
_shtab_luna_service_dhcp_reload__h_nargs=0
_shtab_luna_service_dhcp_reload___help_nargs=0
_shtab_luna_service_dhcp_reload__v_nargs=0
_shtab_luna_service_dhcp_reload___verbose_nargs=0
_shtab_luna_service_dhcp_status__h_nargs=0
_shtab_luna_service_dhcp_status___help_nargs=0
_shtab_luna_service_dhcp_status__v_nargs=0
_shtab_luna_service_dhcp_status___verbose_nargs=0
_shtab_luna_service_dns_pos_0_nargs=A...
_shtab_luna_service_dns__h_nargs=0
_shtab_luna_service_dns___help_nargs=0
_shtab_luna_service_dns_start__h_nargs=0
_shtab_luna_service_dns_start___help_nargs=0
_shtab_luna_service_dns_start__v_nargs=0
_shtab_luna_service_dns_start___verbose_nargs=0
_shtab_luna_service_dns_stop__h_nargs=0
_shtab_luna_service_dns_stop___help_nargs=0
_shtab_luna_service_dns_stop__v_nargs=0
_shtab_luna_service_dns_stop___verbose_nargs=0
_shtab_luna_service_dns_restart__h_nargs=0
_shtab_luna_service_dns_restart___help_nargs=0
_shtab_luna_service_dns_restart__v_nargs=0
_shtab_luna_service_dns_restart___verbose_nargs=0
_shtab_luna_service_dns_reload__h_nargs=0
_shtab_luna_service_dns_reload___help_nargs=0
_shtab_luna_service_dns_reload__v_nargs=0
_shtab_luna_service_dns_reload___verbose_nargs=0
_shtab_luna_service_dns_status__h_nargs=0
_shtab_luna_service_dns_status___help_nargs=0
_shtab_luna_service_dns_status__v_nargs=0
_shtab_luna_service_dns_status___verbose_nargs=0
_shtab_luna_service_luna2_pos_0_nargs=A...
_shtab_luna_service_luna2__h_nargs=0
_shtab_luna_service_luna2___help_nargs=0
_shtab_luna_service_luna2_start__h_nargs=0
_shtab_luna_service_luna2_start___help_nargs=0
_shtab_luna_service_luna2_start__v_nargs=0
_shtab_luna_service_luna2_start___verbose_nargs=0
_shtab_luna_service_luna2_stop__h_nargs=0
_shtab_luna_service_luna2_stop___help_nargs=0
_shtab_luna_service_luna2_stop__v_nargs=0
_shtab_luna_service_luna2_stop___verbose_nargs=0
_shtab_luna_service_luna2_restart__h_nargs=0
_shtab_luna_service_luna2_restart___help_nargs=0
_shtab_luna_service_luna2_restart__v_nargs=0
_shtab_luna_service_luna2_restart___verbose_nargs=0
_shtab_luna_service_luna2_reload__h_nargs=0
_shtab_luna_service_luna2_reload___help_nargs=0
_shtab_luna_service_luna2_reload__v_nargs=0
_shtab_luna_service_luna2_reload___verbose_nargs=0
_shtab_luna_service_luna2_status__h_nargs=0
_shtab_luna_service_luna2_status___help_nargs=0
_shtab_luna_service_luna2_status__v_nargs=0
_shtab_luna_service_luna2_status___verbose_nargs=0
_shtab_luna_control_pos_0_nargs=A...
_shtab_luna_control__h_nargs=0
_shtab_luna_control___help_nargs=0
_shtab_luna_control_power_pos_0_nargs=A...
_shtab_luna_control_power__h_nargs=0
_shtab_luna_control_power___help_nargs=0
_shtab_luna_control_power_on__h_nargs=0
_shtab_luna_control_power_on___help_nargs=0
_shtab_luna_control_power_on__v_nargs=0
_shtab_luna_control_power_on___verbose_nargs=0
_shtab_luna_control_power_off__h_nargs=0
_shtab_luna_control_power_off___help_nargs=0
_shtab_luna_control_power_off__v_nargs=0
_shtab_luna_control_power_off___verbose_nargs=0
_shtab_luna_control_power_status__h_nargs=0
_shtab_luna_control_power_status___help_nargs=0
_shtab_luna_control_power_status__v_nargs=0
_shtab_luna_control_power_status___verbose_nargs=0
_shtab_luna_control_power_reset__h_nargs=0
_shtab_luna_control_power_reset___help_nargs=0
_shtab_luna_control_power_reset__v_nargs=0
_shtab_luna_control_power_reset___verbose_nargs=0
_shtab_luna_control_sel_pos_0_nargs=A...
_shtab_luna_control_sel__h_nargs=0
_shtab_luna_control_sel___help_nargs=0
_shtab_luna_control_sel_list__h_nargs=0
_shtab_luna_control_sel_list___help_nargs=0
_shtab_luna_control_sel_list__v_nargs=0
_shtab_luna_control_sel_list___verbose_nargs=0
_shtab_luna_control_sel_clear__h_nargs=0
_shtab_luna_control_sel_clear___help_nargs=0
_shtab_luna_control_sel_clear__v_nargs=0
_shtab_luna_control_sel_clear___verbose_nargs=0
_shtab_luna_control_chassis_pos_0_nargs=A...
_shtab_luna_control_chassis__h_nargs=0
_shtab_luna_control_chassis___help_nargs=0
_shtab_luna_control_chassis_identify__h_nargs=0
_shtab_luna_control_chassis_identify___help_nargs=0
_shtab_luna_control_chassis_identify__v_nargs=0
_shtab_luna_control_chassis_identify___verbose_nargs=0
_shtab_luna_control_chassis_noidentify__h_nargs=0
_shtab_luna_control_chassis_noidentify___help_nargs=0
_shtab_luna_control_chassis_noidentify__v_nargs=0
_shtab_luna_control_chassis_noidentify___verbose_nargs=0
_shtab_luna_control_redfish_pos_0_nargs=A...
_shtab_luna_control_redfish__h_nargs=0
_shtab_luna_control_redfish___help_nargs=0
_shtab_luna_control_redfish_upload__h_nargs=0
_shtab_luna_control_redfish_upload___help_nargs=0
_shtab_luna_control_redfish_upload__v_nargs=0
_shtab_luna_control_redfish_upload___verbose_nargs=0
_shtab_luna_control_redfish_setting__h_nargs=0
_shtab_luna_control_redfish_setting___help_nargs=0
_shtab_luna_control_redfish_setting__v_nargs=0
_shtab_luna_control_redfish_setting___verbose_nargs=0
_shtab_luna_monitor_pos_0_nargs=A...
_shtab_luna_monitor__h_nargs=0
_shtab_luna_monitor___help_nargs=0
_shtab_luna_monitor__v_nargs=0
_shtab_luna_monitor___verbose_nargs=0
_shtab_luna_monitor_status__h_nargs=0
_shtab_luna_monitor_status___help_nargs=0
_shtab_luna_monitor_status__v_nargs=0
_shtab_luna_monitor_status___verbose_nargs=0
_shtab_luna_monitor_status__R_nargs=0
_shtab_luna_monitor_status___raw_nargs=0
_shtab_luna_monitor_queue__h_nargs=0
_shtab_luna_monitor_queue___help_nargs=0
_shtab_luna_monitor_queue__v_nargs=0
_shtab_luna_monitor_queue___verbose_nargs=0
_shtab_luna_monitor_queue__R_nargs=0
_shtab_luna_monitor_queue___raw_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_luna() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_luna
  local word_index=0
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
      # valid subcommand: add it to the prefix & reset the current action
      prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
      _set_parser_defaults
    fi

    if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
      # a new action should be acquired (due to recognised option string or
      # no more input expected from current action);
      # the next positional action can fill in here
      _set_new_action $this_word false
    fi

    if [[ "$current_action_nargs" != "*" ]] && \
       [[ "$current_action_nargs" != "+" ]] && \
       [[ "$current_action_nargs" != *"..." ]] && \
       (( $word_index + 1 - $current_action_args_start_index >= \
          $current_action_nargs )); then
      $current_action_is_positional && let "completed_positional_actions += 1"
      _set_new_action "pos_${completed_positional_actions}" true
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_luna luna

